/* Mock data — plausible Romanian construction / public procurement content. */

const MOCK_PROJECTS = [
  {
    id: "p-001",
    name: "Reabilitare Pod Rutier DN1 km 127+340",
    description: "CNAIR — Reabilitare structură pod peste Râul Prahova",
    authority: "CNAIR S.A.",
    value: "€ 14.2M",
    created: "2026-04-12",
    status: "evaluated",
    compliance: 86,
    counts: { conform: 142, neconform: 11, partial: 14, insuf: 8 },
  },
  {
    id: "p-002",
    name: "Construcție Școală Gimnazială Sector 4",
    description: "Primăria Sector 4 București — clădire P+2, 18 săli de clasă",
    authority: "Primăria Sect. 4",
    value: "€ 6.8M",
    created: "2026-04-18",
    status: "evaluation_running",
    progress: 0.62,
    compliance: null,
    counts: { conform: 48, neconform: 4, partial: 6, insuf: 2 },
  },
  {
    id: "p-003",
    name: "Extindere Stație Epurare Ape Uzate Bacău",
    description: "Compania de Apă Bacău — stație tip AT2, Q=45.000 mc/zi",
    authority: "CA Bacău S.A.",
    value: "€ 22.4M",
    created: "2026-04-15",
    status: "requirements_extracted",
    compliance: null,
  },
  {
    id: "p-004",
    name: "Modernizare DJ 710A Pucioasa–Moreni",
    description: "CJ Dâmbovița — 14.3 km, 2 benzi, asfalt MAS 16",
    authority: "CJ Dâmbovița",
    value: "€ 9.1M",
    created: "2026-04-19",
    status: "documents_ready",
    compliance: null,
  },
  {
    id: "p-005",
    name: "Bloc Locuințe Colective ANL Iași",
    description: "P+4+M, 48 unități locative, str. Moara de Vânt",
    authority: "ANL",
    value: "€ 4.3M",
    created: "2026-04-19",
    status: "documents_ready",
    compliance: null,
  },
  {
    id: "p-006",
    name: "Centru de Management Integrat Deșeuri Vâlcea",
    description: "ADI Salubrizare Vâlcea — sortare + compostare 45.000 t/an",
    authority: "ADI Vâlcea",
    value: "€ 18.9M",
    created: "2026-04-20",
    status: "created",
    compliance: null,
  },
  {
    id: "p-007",
    name: "Reabilitare Termică Spital Județean Arad",
    description: "CJ Arad — anvelopă + instalații pt. Pavilion Principal",
    authority: "CJ Arad",
    value: "€ 3.2M",
    created: "2026-03-28",
    status: "evaluated",
    compliance: 94,
    counts: { conform: 98, neconform: 2, partial: 5, insuf: 1 },
  },
  {
    id: "p-008",
    name: "Piste Biciclete Centura Cluj-Napoca",
    description: "Primăria Cluj-Napoca — 8.4 km, racord parcuri urbane",
    authority: "Primăria Cluj",
    value: "€ 2.1M",
    created: "2026-03-30",
    status: "error",
    compliance: null,
  },
];

const STATUS_LABEL = {
  created: { label: "Creat", dot: "warn" },
  documents_ready: { label: "Documente procesate", dot: "ok" },
  requirements_extracted: { label: "Cerințe extrase", dot: "ok" },
  evaluation_running: { label: "Evaluare în curs", dot: "live" },
  evaluated: { label: "Evaluat", dot: "ok" },
  error: { label: "Eroare", dot: "err" },
};

const MOCK_DOCUMENTS = [
  { id: "d1", type: "CS",  name: "Caiet_Sarcini_Pod_DN1_v3.docx",        size: "4.2 MB", pages: 237, headings: 148, status: "ready" },
  { id: "d2", type: "CS",  name: "Anexa_Tehnica_Pile_Fundatii.docx",       size: "1.8 MB", pages: 62,  headings: 34,  status: "ready" },
  { id: "d3", type: "FDA", name: "Fisa_Date_Achizitie_2026-04-12.docx",   size: "0.6 MB", pages: 28,  headings: 19,  status: "ready" },
  { id: "d4", type: "PT",  name: "Propunere_Tehnica_SC_ConstruxA_SA.docx",size: "11.4 MB",pages: 412, headings: 276, status: "ready" },
];

const MOCK_REQUIREMENTS = [
  {
    id: "REQ-0142",
    section: "Cap. 3 › 3.2 Materiale › 3.2.1 Beton",
    text: "Betonul utilizat pentru suprastructură va fi clasă minimă C35/45, cu clasă de expunere XC4+XD3+XF4 conform SR EN 206+A2:2021, având un conținut minim de ciment de 360 kg/m³ și raport apă/ciment ≤ 0.45.",
    category: "materiale",
    priority: "obligatoriu",
    verification: "match_value",
    standards: ["SR EN 206+A2:2021", "NE 012/1-2022"],
    confidence: 0.94,
    flagged: false,
  },
  {
    id: "REQ-0143",
    section: "Cap. 3 › 3.2 Materiale › 3.2.1 Beton",
    text: "Agregatele vor respecta cerințele SR EN 12620+A1:2008, cu granulozitate maximă 22 mm pentru elementele de suprastructură și 31.5 mm pentru infrastructură.",
    category: "materiale",
    priority: "obligatoriu",
    verification: "match_value",
    standards: ["SR EN 12620+A1:2008"],
    confidence: 0.91,
    flagged: false,
  },
  {
    id: "REQ-0144",
    section: "Cap. 3 › 3.2 Materiale › 3.2.2 Oțel",
    text: "Armătura activă va fi toroane din sârmă trasă conform SR EN 10138-3:2013, clasa Y1860S7, cu relaxare redusă (Clasa 2).",
    category: "materiale",
    priority: "obligatoriu",
    verification: "match_reference",
    standards: ["SR EN 10138-3:2013"],
    confidence: 0.88,
    flagged: false,
  },
  {
    id: "REQ-0145",
    section: "Cap. 3 › 3.2 Materiale › 3.2.2 Oțel",
    text: "Oțelul pentru armături nepretensionate va fi BST500S conform SR 438-1:2012 sau echivalent, cu diametre între Ø8 și Ø32 mm.",
    category: "materiale",
    priority: "obligatoriu",
    verification: "match_value",
    standards: ["SR 438-1:2012"],
    confidence: 0.72,
    flagged: true,
  },
  {
    id: "REQ-0208",
    section: "Cap. 4 › 4.1 Execuție › 4.1.3 Cofraje",
    text: "Cofrajele utilizate vor fi metalice de tip cadru sau din placaj fenolic hidrofug cu grosime minimă 18 mm, asigurând o abatere de planeitate ≤ 3 mm / 2 m.",
    category: "tehnic",
    priority: "obligatoriu",
    verification: "match_description",
    standards: ["STAS 7721-90"],
    confidence: 0.86,
    flagged: false,
  },
  {
    id: "REQ-0301",
    section: "Cap. 5 › 5.2 Controlul calității",
    text: "Ofertantul va prezenta Planul Calității conform SR EN ISO 9001:2015, cu proceduri specifice pentru fiecare proces critic identificat.",
    category: "calitate",
    priority: "obligatoriu",
    verification: "match_reference",
    standards: ["SR EN ISO 9001:2015"],
    confidence: 0.95,
    flagged: false,
  },
  {
    id: "REQ-0302",
    section: "Cap. 5 › 5.2 Controlul calității",
    text: "Se vor efectua încercări pe epruvete de beton la vârsta de 7 și 28 zile, minim 1 serie la 50 m³ turnat, cu raportare către laborator autorizat ISC.",
    category: "calitate",
    priority: "obligatoriu",
    verification: "match_value",
    standards: ["SR EN 12390-3:2019"],
    confidence: 0.89,
    flagged: false,
  },
  {
    id: "REQ-0410",
    section: "Cap. 6 › 6.1 Resurse umane",
    text: "Șef șantier atestat MLPDA cu experiență minimă 10 ani în lucrări de artă (poduri / viaducte) și minim 3 proiecte similare finalizate.",
    category: "personal",
    priority: "obligatoriu",
    verification: "match_description",
    standards: [],
    confidence: 0.81,
    flagged: false,
  },
  {
    id: "REQ-0411",
    section: "Cap. 6 › 6.1 Resurse umane",
    text: "Responsabil tehnic cu execuția (RTE) atestat conform Ord. 1496/2011 pentru domeniul IX – construcții hidrotehnice și poduri.",
    category: "personal",
    priority: "obligatoriu",
    verification: "match_reference",
    standards: [],
    confidence: 0.90,
    flagged: false,
  },
  {
    id: "REQ-0520",
    section: "Cap. 7 › 7.3 Termene",
    text: "Durata maximă de execuție: 18 luni calendaristice de la ordinul de începere; graficul Gantt va include milestone-urile T0, T+90, T+180, T+360, T+540.",
    category: "termene",
    priority: "obligatoriu",
    verification: "match_value",
    standards: [],
    confidence: 0.93,
    flagged: false,
  },
  {
    id: "REQ-0521",
    section: "Cap. 7 › 7.3 Termene",
    text: "Perioada de garanție: minim 60 luni de la recepție la terminarea lucrărilor pentru structura de rezistență.",
    category: "termene",
    priority: "obligatoriu",
    verification: "match_value",
    standards: [],
    confidence: 0.97,
    flagged: false,
  },
  {
    id: "REQ-0612",
    section: "Cap. 8 › 8.2 Echipamente",
    text: "Utilaje minime: macara turn min. 250 tm, pompă beton cu braț ≥ 42 m, autobetoniere ≥ 5 buc. de min. 9 m³ fiecare.",
    category: "echipamente",
    priority: "recomandat",
    verification: "match_description",
    standards: [],
    confidence: 0.79,
    flagged: true,
  },
];

const REQUIREMENT_CATEGORIES = [
  { key: "tehnic",       label: "Tehnic",       count: 94 },
  { key: "materiale",    label: "Materiale",    count: 52 },
  { key: "calitate",     label: "Calitate",     count: 28 },
  { key: "termene",      label: "Termene",      count: 14 },
  { key: "personal",     label: "Personal",     count: 18 },
  { key: "echipamente",  label: "Echipamente",  count: 11 },
  { key: "administrativ",label: "Administrativ", count: 8 },
];

const MOCK_EVAL_RESULTS = [
  {
    id: "EV-0142",
    reqId: "REQ-0142",
    verdict: "CONFORM",
    confidence: 0.93,
    req: "Betonul utilizat pentru suprastructură va fi clasă minimă C35/45, clasă expunere XC4+XD3+XF4, min. 360 kg ciment/m³, a/c ≤ 0.45.",
    reasoning: "PT-ul ofertantului specifică explicit clasa C40/50 (superioară cerinței minime C35/45), clasa de expunere identică cu CS, dozaj ciment de 380 kg/m³ și raport a/c = 0.42. Toate valorile sunt mai stricte decât cerința minimă.",
    covered: ["Clasă rezistență", "Clasă expunere", "Dozaj ciment", "Raport apă/ciment"],
    missing: [],
    quotes: [
      {
        text: "Pentru elementele de suprastructură se utilizează beton clasa C40/50, clasa de expunere XC4+XD3+XF4 conform SR EN 206+A2:2021, dozaj minim de ciment 380 kg/m³ (CEM II/A-S 42.5R), raport apă/ciment maxim 0.42.",
        source: "Propunere_Tehnica_SC_ConstruxA_SA.docx",
        section: "§ 4.2.1 Betoane — Suprastructură",
        page: 87,
        verified: true,
      },
    ],
    cs: { section: "Cap. 3 › 3.2.1 Beton", page: 42 },
  },
  {
    id: "EV-0145",
    reqId: "REQ-0145",
    verdict: "NECONFORM",
    confidence: 0.88,
    req: "Oțel armături nepretensionate BST500S conform SR 438-1:2012, Ø8–Ø32 mm.",
    reasoning: "Ofertantul menționează OB37 (oțel beton cu limită de curgere 235 N/mm²) pentru armături constructive — aceasta este o clasă inferioară față de BST500S (500 N/mm²). Deși BST500S apare în lista generală, utilizarea efectivă descrisă folosește OB37 pentru elemente structurale critice.",
    covered: ["Diametre armături"],
    missing: ["Clasa BST500S pentru toate armăturile", "Conformitate SR 438-1:2012 integrală"],
    quotes: [
      {
        text: "Armăturile constructive ale cuzineților și ale elementelor secundare vor fi executate din oțel OB37 (fyk = 235 N/mm²), conform SR 438-1:2012.",
        source: "Propunere_Tehnica_SC_ConstruxA_SA.docx",
        section: "§ 4.2.2 Armături — Elemente secundare",
        page: 92,
        verified: true,
      },
    ],
    cs: { section: "Cap. 3 › 3.2.2 Oțel", page: 48 },
    flags: ["critical"],
  },
  {
    id: "EV-0208",
    reqId: "REQ-0208",
    verdict: "PARTIAL",
    confidence: 0.74,
    req: "Cofraje metalice cadru sau placaj fenolic hidrofug ≥18 mm, abatere planeitate ≤ 3 mm / 2 m.",
    reasoning: "PT-ul descrie cofraje din placaj fenolic de 21 mm (conform), dar nu menționează explicit tolerança de planeitate. Se presupune conformitate prin standardul referențiat, însă verificarea directă lipsește.",
    covered: ["Tip cofraj", "Grosime minimă"],
    missing: ["Specificație explicită a toleranței de planeitate"],
    quotes: [
      {
        text: "Se vor utiliza cofraje din placaj fenolic hidrofug de 21 mm grosime, marca Finsa sau echivalent, refolosibile min. 40 ori.",
        source: "Propunere_Tehnica_SC_ConstruxA_SA.docx",
        section: "§ 5.1.3 Tehnologii de cofrare",
        page: 143,
        verified: true,
      },
    ],
    cs: { section: "Cap. 4 › 4.1.3 Cofraje", page: 71 },
  },
  {
    id: "EV-0302",
    reqId: "REQ-0302",
    verdict: "CONFORM",
    confidence: 0.96,
    req: "Încercări pe epruvete de beton la 7 și 28 zile, min. 1 serie / 50 m³, laborator ISC.",
    reasoning: "Propunerea prezintă protocol complet cu frecvență 1 serie/40 m³ (mai strict decât cerut), încercări la 7/14/28 zile și contract cu laborator acreditat RENAR.",
    covered: ["Vârste încercare", "Frecvență minimă", "Laborator autorizat"],
    missing: [],
    quotes: [
      {
        text: "Planul de control al calității prevede încercări pe epruvete cubice 150 mm la vârstele de 7, 14 și 28 zile, frecvența minimă 1 serie la fiecare 40 m³ de beton turnat, efectuate de Laboratorul CESTRIN (acreditat RENAR LI-0142).",
        source: "Propunere_Tehnica_SC_ConstruxA_SA.docx",
        section: "§ 8.2 Planul de Control",
        page: 256,
        verified: true,
      },
    ],
    cs: { section: "Cap. 5 › 5.2 Control calitate", page: 98 },
  },
  {
    id: "EV-0411",
    reqId: "REQ-0411",
    verdict: "INSUFFICIENT_DATA",
    confidence: 0.42,
    req: "RTE atestat Ord. 1496/2011 dom. IX — construcții hidrotehnice și poduri.",
    reasoning: "PT-ul listează RTE cu nume și număr atestat, dar domeniul atestării (IX) nu apare explicit în fragmentul recuperat. CV-ul este menționat în anexă — anexa nu a putut fi corelată automat.",
    covered: ["Existența RTE nominalizat"],
    missing: ["Dovada explicită a atestării pe domeniul IX"],
    quotes: [
      {
        text: "Responsabil Tehnic cu Execuția: ing. Mihai Popescu, atestat MLPDA nr. 21847 / 2019. CV-ul și copia atestatului sunt prezentate în Anexa PT-06.",
        source: "Propunere_Tehnica_SC_ConstruxA_SA.docx",
        section: "§ 9.1 Personal cheie",
        page: 298,
        verified: true,
      },
    ],
    cs: { section: "Cap. 6 › 6.1 Resurse umane", page: 132 },
    flags: ["needs_review"],
  },
  {
    id: "EV-0520",
    reqId: "REQ-0520",
    verdict: "CONFORM",
    confidence: 0.91,
    req: "Durată execuție ≤ 18 luni, grafic Gantt cu milestone-uri T0–T+540.",
    reasoning: "Propunerea prezintă durată de 17 luni cu toate milestone-urile solicitate detaliate în graficul Gantt anexat.",
    covered: ["Durată totală", "Milestone-uri", "Grafic Gantt"],
    missing: [],
    quotes: [
      {
        text: "Durata de execuție propusă: 17 luni calendaristice. Graficul Gantt (Anexa PT-11) include toate milestone-urile T0, T+90, T+180, T+360, T+540.",
        source: "Propunere_Tehnica_SC_ConstruxA_SA.docx",
        section: "§ 10.2 Termene",
        page: 331,
        verified: true,
      },
    ],
    cs: { section: "Cap. 7 › 7.3 Termene", page: 168 },
  },
  {
    id: "EV-0612",
    reqId: "REQ-0612",
    verdict: "PARTIAL",
    confidence: 0.68,
    req: "Macara turn ≥ 250 tm, pompă beton braț ≥ 42 m, ≥5 autobetoniere de 9 m³.",
    reasoning: "Pompă beton (47 m) și autobetoniere (6 buc. × 10 m³) sunt conforme. Macaraua turn propusă este de 220 tm, sub valoarea minimă cerută. Justificarea ofertantului invocă utilizare în tandem cu macara mobilă, însă CS-ul nu permite echivalențe pentru acest parametru.",
    covered: ["Pompă beton", "Autobetoniere"],
    missing: ["Macara turn cu capacitate ≥ 250 tm"],
    quotes: [
      {
        text: "Macara turn Liebherr 154 EC-H (220 tm capacitate) operând în tandem cu macara mobilă LTM 1100 (100 t) pentru operațiuni critice care depășesc parametrii macaralei turn.",
        source: "Propunere_Tehnica_SC_ConstruxA_SA.docx",
        section: "§ 11.3 Utilaje și echipamente",
        page: 378,
        verified: true,
      },
    ],
    cs: { section: "Cap. 8 › 8.2 Echipamente", page: 189 },
    flags: ["quote_unverified"],
  },
];

const VERDICT_TOTALS = { conform: 142, neconform: 11, partial: 14, insuf: 8 };

const PIPELINE_STAGES = [
  { key: "documents",    label: "Documente",   sub: "Parsare, indexare, chunking" },
  { key: "requirements", label: "Cerințe",     sub: "Extragere atomică via LLM" },
  { key: "evaluation",   label: "Evaluare",    sub: "Retrieval + verdicte" },
  { key: "report",       label: "Raport",      sub: "Sinteză și export" },
];

Object.assign(window, {
  MOCK_PROJECTS, STATUS_LABEL,
  MOCK_DOCUMENTS, MOCK_REQUIREMENTS, REQUIREMENT_CATEGORIES,
  MOCK_EVAL_RESULTS, VERDICT_TOTALS, PIPELINE_STAGES,
});
